baseurl = "https://example.org/"
title = "Helena Fogelberg"
theme = "hugo-creative-portfolio-theme"
languageCode = "sv-se"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  # Create css/custom.css in your <<base dir>>/static for custom styling.
  style = "violet"
  description = "Helena Fogelberg"
  copyright = "&copy;2022 Helena Fogelberg\n"
  sidebarAbout = [
    "Jag är en konstnär och illustratör som bor i Malmö.",
    "Jag tycker särskilt om att måla djur, natur och abstrakta fantasimotiv.\n"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Hem"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Djur"
  url = "djur/"

  [[params.navlinks]]
  name = "Om"
  url = "about/"

  # [[params.navlinks]]
  # name = "Kontakt"
  # url = "contact/"

  [params.social]
  email         = "helena.d.fogelberg@gmail.com"
